name: Update Notion with Pull Request Information

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Task Number
        id: extract
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "Pull Request Title: $PR_TITLE"
          TASK_NUMBER=$(echo "$PR_TITLE" | grep -oE 'TASK-[0-9]+' | grep -oE '[0-9]+')
          echo "Extracted Task Number: $TASK_NUMBER"
          echo "TASK_NUMBER=$TASK_NUMBER" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
          echo "PR_ID=${{ github.event.pull_request.id }}" >> $GITHUB_ENV
          PR_STATE="${{ github.event.pull_request.state }}"
          PR_MERGED="${{ github.event.pull_request.merged }}"
          if [ "$PR_STATE" = "closed" ] && [ "$PR_MERGED" = "true" ]; then
            PR_STATUS="merged"
            ICON_EMOJI="🎉"
          else
            PR_STATUS="$PR_STATE"
            ICON_EMOJI="🔧"
          fi
          echo "PR_STATUS=$PR_STATUS" >> $GITHUB_ENV
          echo "ICON_EMOJI=$ICON_EMOJI" >> $GITHUB_ENV

      - name: Debug Task Number
        run: echo "Task Number is ${{ env.TASK_NUMBER }}"

      - name: Update Notion
        if: env.TASK_NUMBER
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_TASK_DATABASE_ID: ${{ secrets.NOTION_TASK_DATABASE_ID }}
          NOTION_PR_DATABASE_ID: ${{ secrets.NOTION_PR_DATABASE_ID }}
          TASK_NUMBER: ${{ env.TASK_NUMBER }}
          PR_URL: ${{ env.PR_URL }}
          PR_ID: ${{ env.PR_ID }}
          PR_STATUS: ${{ env.PR_STATUS }}
          PR_TITLE: ${{ env.PR_TITLE }}
          ICON_EMOJI: ${{ env.ICON_EMOJI }}
        run: |
          echo "Querying Notion for Task Number: $TASK_NUMBER"
          TASK_QUERY_RESPONSE=$(curl -s -X POST "https://api.notion.com/v1/databases/$NOTION_TASK_DATABASE_ID/query" \
            -H "Authorization: Bearer $NOTION_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data "{\"filter\":{\"property\":\"ID\",\"unique_id\":{\"equals\":$TASK_NUMBER}}}")
          echo "Task Query Response: $TASK_QUERY_RESPONSE"
          TASK_ID=$(echo $TASK_QUERY_RESPONSE | jq -r '.results[0].id')
          echo "Task ID: $TASK_ID"

          if [ "$TASK_ID" != "null" ]; then
            echo "Updating or Creating Pull Request entry in Notion"
            PR_QUERY_RESPONSE=$(curl -s -X POST "https://api.notion.com/v1/databases/$NOTION_PR_DATABASE_ID/query" \
              -H "Authorization: Bearer $NOTION_API_KEY" \
              -H "Content-Type: application/json" \
              -H "Notion-Version: 2022-06-28" \
              --data "{\"filter\":{\"property\":\"PR ID\",\"number\":{\"equals\":$PR_ID}}}")
            echo "PR Query Response: $PR_QUERY_RESPONSE"
            PR_PAGE_ID=$(echo $PR_QUERY_RESPONSE | jq -r '.results[0].id')
            echo "PR Page ID: $PR_PAGE_ID"

            if [ "$PR_PAGE_ID" != "null" ]; then
              echo "Updating existing PR entry"
              echo "PR TITLE is $PR_TITLE"
              curl -s -X PATCH "https://api.notion.com/v1/pages/$PR_PAGE_ID" \
                -H "Authorization: Bearer $NOTION_API_KEY" \
                -H "Content-Type: application/json" \
                -H "Notion-Version: 2022-06-28" \
                --data "{\"properties\":{\"Name\":{\"title\":[{\"text\":{\"content\":\"$PR_TITLE\"}}]},\"Status\":{\"select\":{\"name\":\"$PR_STATUS\"}},\"URL\":{\"url\":\"$PR_URL\"},\"Task\":{\"relation\":[{\"id\":\"$TASK_ID\"}],\"icon\":{\"type\":\"emoji\",\"emoji\":\"$ICON_EMOJI\"}}}"
            else
              echo "Creating new PR entry"
              curl -s -X POST "https://api.notion.com/v1/pages" \
                -H "Authorization: Bearer $NOTION_API_KEY" \
                -H "Content-Type: application/json" \
                -H "Notion-Version: 2022-06-28" \
                --data "{
                  \"parent\": { \"database_id\": \"$NOTION_PR_DATABASE_ID\" },
                  \"properties\": {
                    \"PR ID\": { \"number\": $PR_ID },
                    \"Name\": { \"title\": [{ \"text\": { \"content\": \"$PR_TITLE\" }}] },
                    \"Status\": { \"select\": { \"name\": \"$PR_STATUS\" } },
                    \"URL\": { \"url\": \"$PR_URL\" },
                    \"Task\": { \"relation\": [{ \"id\": \"$TASK_ID\" }] }
                  },
                  \"icon\": { \"type\": \"emoji\", \"emoji\": \"$ICON_EMOJI\" }
                }"
            fi
          else
            echo "No task found for Task Number: $TASK_NUMBER"
          fi
