name: Update Notion with Pull Request URL

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-notion:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Task Number
      id: extract
      run: |
        PR_TITLE="${{ github.event.pull_request.title }}"
        echo "Pull Request Title: $PR_TITLE"
        TASK_NUMBER=$(echo "$PR_TITLE" | grep -oE 'TASK-[0-9]+' | grep -oE '[0-9]+')
        echo "Extracted Task Number: $TASK_NUMBER"
        echo "TASK_NUMBER=$TASK_NUMBER" >> $GITHUB_ENV
    
    - name: Debug Task Number
      run: echo "Task Number is ${{ env.TASK_NUMBER }}"

    - name: Debug Secrets
      run: |
        echo "Notion Key is ${{ secrets.NOTION_API_KEY }}"
        echo "Database ID is ${{ secrets.NOTION_DATABASE_ID }}"

    - name: Update Notion
      if: env.TASK_NUMBER
      env:
        NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        TASK_NUMBER: ${{ env.TASK_NUMBER }}
        PR_URL: ${{ github.event.pull_request.html_url }}
      run: |
        echo "Querying Notion for Task Number: $TASK_NUMBER"
        RESPONSE=$(curl -X POST 'https://api.notion.com/v1/databases/$NOTION_DATABASE_ID/query' \
          -H "Authorization: Bearer $NOTION_API_KEY" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data '{
            "filter": {
              "property": "ID",
              "unique_id": {
                "equals": "'"$TASK_NUMBER"'"
              }
            }
          }')
        echo "Notion Query Response: $RESPONSE"
        PAGE_ID=$(echo $RESPONSE | jq -r '.results[0].id')
        echo "Page ID: $PAGE_ID"

        if [ "$PAGE_ID" != "null" ]; then
          echo "Updating Notion page with Pull Request URL: $PR_URL"
          UPDATE_RESPONSE=$(curl -X PATCH "https://api.notion.com/v1/pages/$PAGE_ID" \
            -H "Authorization: Bearer $NOTION_API_KEY" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data '{
              "properties": {
                "My Github PR": {
                  "url": "'"$PR_URL"'"
                }
              }
            }')
          echo "Notion Update Response: $UPDATE_RESPONSE"
        else
          echo "No page found for Task Number: $TASK_NUMBER"
        fi
